# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: area_dum
  username: area_dum
  password: area_dum
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: area_dum
  username: area_dum
  password: area_dum
  host: http://qeast.qeastsearch.com/
  port: 5432